version: "3.6"
services:
  orange-data:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: orange-data
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keys:/app/dist/shared/keys:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orange-data.entrypoints=http"
      - "traefik.http.routers.orange-data.rule=Host(`orange.${DOMAIN}`)"
      - "traefik.http.middlewares.orange-data-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.orange-data.middlewares=orange-data-https-redirect"
      - "traefik.http.routers.orange-data-secure.entrypoints=https"
      - "traefik.http.routers.orange-data-secure.rule=Host(`orange.${DOMAIN}`)"
      - "traefik.http.routers.orange-data-secure.tls=true"
      - "traefik.http.routers.orange-data-secure.tls.certresolver=http"
      - "traefik.http.routers.orange-data-secure.service=orange-data"
      - "traefik.http.services.orange-data.loadbalancer.server.port=3000"
    networks:
      - net

networks:
  net:
    external: true
